spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/FitnessActivity
      database: FitnessActivity
    rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest
  #mongodb://localhost:27017/
server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

rabbitmq:
  exchange:
    name: fitness.exchange
  queue:
    name: activity.queue
  routing:
    key: activity.tracking
user:
  service:
    uri: http://USER-SERVICE