spring:
  dataSource:
    url: jdbc:postgresql://localhost:5432/demo
    userName: praveen
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
